# Description of author
author: Jiaming Xiao
bio: My personal blog of tech and life

# Name of the website
name: Jiaming's Blog
title: Jiaming's Blog

# Web-page description
description: A personal web-page for Jiaming

# Self profile image
external-image: false
picture:

# If a resume needs to be included, set to true
resume: false
resume-external: false
resume-url:

# Personal url
url: https://jeremyincmu.github.io

permalink: /:title/

# If comments are not necessary, then leave categories empty
disqus:
  shortname: mydisqus # enter this from disqus account
  categories: [blog, projects] # only show disqus for posts that have these categories

# Add social below like facebook,twitter and github
github: JeremyInCMU
email: jiamingx@andrew.cmu.edu
#twitter: Jeremy
#linkedin: Jeremy
#facebook: Jeremy

#if a large site needed, then change the option below
# options: [normal, large] | default: normal
# normal = 560px / large = 810px
width: nomral

# if you don't need pagination, comment the *paginate* configs below
paginate: 5
paginate_path: "blog/:num/"

# Display links for next and previous posts for the specified categories
post-advance-links: [blog]

# if you don't need "about" or "blog", comment them out below
about: true
blog: true
projects: true
resume: true

# show the "tags" inside the posts
show-tags: true

# show read-time of the posts
read-time: true

# Related posts inside a post
related: true

# show author of the posts
show-author: true

# plug-ins
plug-ins:
    - jekyll-seo-tag
    - jekyll-gist
    - jekyll-feed
    - jemoji
    - jekyll-admin

theme: minima
github: [metadata]

# if site needs animation
animation: true
